### ISSUE TITLE
当日期在12月30日和31日的时候，年变成了2019年。

### ISSUE THREAD

**Issue by ZM0709** [qingfengiOS/QFDatePickerView#1]

**Comment by qingfengiOS** [comment]
我把时间改到了2018-12-31，这边没复现 可以说说具体步骤吗

**Comment by ZM0709** [comment]
你好，是在仿滴滴的那个时间选择器中会出现的情况。把天数添多一点，可以发现选中12月29日的时候年还是2018，但选中12月30日和12月31日，年就变成了2019年。再往下1月1日还是2019年。
或者干脆将手机时间设置为12月29日，就可以复现这种情况。

**Comment by ZM0709** [comment]
日期这么处理的话就会避免这种情况，献丑了。
    NSDate *currentDate = [NSDate date];
    NSDate *appointDate;
    NSTimeInterval oneDay = 24 * 60 * 60;
    for (int i = 0; i < 60; i++) {
        appointDate = [currentDate initWithTimeIntervalSinceNow: oneDay * i];
        NSString *maxTimeStr = [NSDate getTomorrowDay:appointDate];
        [dateArray addObject:maxTimeStr];
    }

+ (NSString *)getTomorrowDay:(NSDate *)Date {
    NSCalendar *gregorian = [[NSCalendar alloc] initWithCalendarIdentifier:NSCalendarIdentifierGregorian];
    NSDateComponents *components = [gregorian components:NSCalendarUnitWeekday | NSCalendarUnitYear | NSCalendarUnitMonth | NSCalendarUnitDay fromDate:aDate];
    [components setDay:([components day]+1)];
    NSDate *beginningOfWeek = [gregorian dateFromComponents:components];
    
    NSDateFormatter *dateday = [[NSDateFormatter alloc] init];
    [dateday setDateFormat:@"yyyy-MM-dd"];
    return [dateday stringFromDate:beginningOfWeek];
}

**Comment by qingfengiOS** [comment]
感谢您的指正并提出解决方案，您的方案完全可行，已修复

**Comment by ZM0709** [comment]
客气了，您这是没有发现这种情况，发现了您也可以很快的解决。
